/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.github.ddth.recipes.apiservice.thrift.def;


public enum TDataEncoding implements org.apache.thrift.TEnum {
  JSON_DEFAULT(0),
  JSON_STRING(1),
  JSON_GZIP(2);

  private final int value;

  private TDataEncoding(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TDataEncoding findByValue(int value) { 
    switch (value) {
      case 0:
        return JSON_DEFAULT;
      case 1:
        return JSON_STRING;
      case 2:
        return JSON_GZIP;
      default:
        return null;
    }
  }
}
